let resource_lang = {
    "vn": {
        "school": "TRƯỜNG ĐẠI HỌC QUỐC TẾ ",
        "school-group": "ĐẠI HỌC QUỐC GIA THÀNH PHỐ HỒ CHÍ MINH",
        "name": "KHOA CÔNG NGHỆ SINH HỌC",
        "portal": "Cổng Thông Tin",
        "search": "Tìm Kiếm",
        "about": "Giới Thiệu",
        "admission": "TUYỂN SINH",
        "academics": "ĐÀO TẠO",
        "research": "NGHIÊN CỨU",
        "students": "SINH VIÊN",
        "news": "TIN TỨC",
        "contact": "LIÊN HỆ",
        "overview": "Tổng Quan",
        "history": "Lịch Sử Hình Thành",
        "dean-s-welcome": "Lời Nói Đầu",
        "vision-and-mission": "Tầm Nhìn & Sứ Mệnh",
        "accreditation": "Chứng Nhận",
        "organization": "Tổ Chức",
        "dean-office": "Ban Chủ Nhiệm Khoa",
        "secretariat": "Ban Thư Ký",
        "departments": "Bộ Môn",
        "departments-news": "Tin Bộ Môn",
        "depatment-of-biotechnology": "Bộ Môn Công Nghệ Sinh Học",
        "department-of-food-technology": "Bộ Môn Công Nghệ Thực Phẩm",
        "department-of-applied-chemistry": "Bộ Môn Hoá Ứng Dụng",
        "department-of-aquascience": "Bộ Môn Khoa Học Thuỷ Sản",
        "laboratories": "Phòng Thí Nghiệm",
        "undergraduate-admission": "Đại Học",
        "graduate-admission": "Sau Đại Học",
        "undergraduate-programs": "Chương Trình Đại Học",
        "dual-undergraduate-programs": "Chương Trình Song Ngành",
        "graduate-programs": "Chương Trình Sau Đại Học",
        "bachelor-s-to-master-s-programs": "Chương Trình Liên Thông Đại Học – Thạc Sĩ",
        "twinning-programs": "Chương Trình Liên Kết",
        "projects-and-publications": "Danh Sách Đề Tài Và Bài Báo",
        "notable-research": "Nghiên Cứu Nổi Bật",
        "hot-news": "Tin Nổi Bật",
        "academic-news": "Tin Học Thuật",
        "research-news": "Tin Nghiên Cứu",
        "students": "Sinh Viên",
        "current-students": "Sinh Viên Hiện Tại",
        "academic-calendar": "Lịch Học",
        "student-handbook": "Sổ Tay Sinh Viên",
        "class-cancellation": "Thông Báo Nghỉ Lớp",
        "laboratory-registration-and-forms": "Đăng Ký Sử Dụng Phòng Thí Nghiệm",
        "forms": "Văn Bản",
        "scholarship-opportunities": "Cơ Hội Học Bổng",
        "prospective-students": "Sinh Viên Tương Lai",
        "admission-information": "Thông Tin Tuyển Sinh",
        "academic-program-information": "Thông Tin Chương Trình Đào Tạo",
        "alumni": "Cựu Sinh Viên",
        "notable-alumni": "Cựu Sinh Viên Tiêu Biểu",
        "alumni-news": "Tin Tức Cựu Sinh Viên",
        "departments-of": "Bộ Môn",
        "biotechnology": "Công Nghệ Sinh Học",
        "food-technology": "Công Nghệ Thực Phẩm",
        "applied-chemistry": "Hoá Ứng Dụng",
        "aquascience": "Khoa Học Thuỷ Sản",
        "promo": "HOẠT ĐỘNG TRẢI NGHIỆM",
        "reg-promo": "THAM GIA TRẢI NGHIỆM",
        "research": "Nghiên cứu",
        "view-all-posts": "Xem tất cả bài viết",
        "view-all-events": "Xem tất cả sự kiện",
        "contact": "Liên hệ",
        "contact-name": "Trường đại học quốc tế - khoa công nghệ sinh học",
        "address-text": "Khu phố 6, phường Linh Trung, TP. Thủ Đức, TP. Hồ Chí Minh",
        "send-message": "Gửi Tin Nhắn",
        "message-contact": "Vui lòng để lại bất kỳ thông tin thắc mắc nào. Chúng tôi sẽ liên hệ với bạn ngay khi nhận được./.",
        "fullname": "Họ tên",
        "phone": "Điện thoại",
        "email": "Thư điện tử",
        "message": "tin nhắn",
        "read-more": "đọc thêm",
        "mission": "Nhiệm vụ",
        "page": "Trang",
        "links": "Liên kết",
        "promo-text": "Khoa Công nghệ Sinh học được thành lập với mong muốn đưa Đại học Quốc tế đi đầu về giáo dục và nghiên cứu trong các lĩnh vực Công nghệ Sinh học, Công nghệ Thực phẩm, Hóa sinh, Khoa học Thủy sản, Kỹ thuật Hóa học và Khoa học Y sinh.",
        "research-text": "Nhiệm vụ của chúng tôi là ứng dụng hiệu quả kết quả học tập và nghiên cứu vào công tác phát triển xã hội.",
        "activities": "Hoạt Động",
        "document-form": "Mẫu Tài Liệu",
        "lecturers": "Giảng viên",
        "manager-lecturers": "Cán bộ & Giảng viên",
        "education-program": "Chương trình đào tạo",
        "career-opportunities": "Cơ hội nghề nghiệp",
        "previous-admission-score": "Điểm Chuẩn Các Năm",
        "strategic-partners": "Đối tác chiến lược",
        "awards-and-products": "Thành tích & Sản phẩm",
        "activities": "Hoạt động",
        "student-list": "Danh sách sinh viên",
        "student-handbook": "Sổ tay sinh viên",
        "internship-program": "Chương trình thực tập",
        "thesis": "Luận văn tốt nghiệp",
        "general-information": "Thông tin chung",
        "programs": "Các ngành học",
        "twinning-program": "Các chương trình liên kết",
        "biotechnology-program": "Ngành Công Nghệ Sinh Học",
        "chemistry-biochemistry-program": "Ngành Hoá học (Hoá sinh)",
        "food-technology-program": "Ngành Công nghệ Thực phẩm",
        "aquascience-program": "Ngành Khoa Học Thủy Sản",
        "twinning-university-of-nottingham": "Liên kết Đại học Nottingham",
        "twinning-university-of-the-west-of-england": "Liên kết Đại học West of England",
        "admission-procedures": "Phương thức xét tuyển",
        "entrance-examination-groups": "Tổ hợp môn xét tuyển",
        "list-of-admissions": "Danh sách nhập học",
        "list-of-graduates": "Danh sách tốt nghiệp",
        "biotechnology-biomedical-science-orientation": "Công nghệ Sinh học định hướng Y sinh",
        "join-us": "Gia nhập",
        "outstanding-alumni": "Gương mặt nổi bật",
        "career-hub": "Tuyển dụng",
    },
    "en": {
        "school": "INTERNATIONAL UNIVERSITY",
        "school-group": "VIETNAM NATIONAL UNIVERSITY HO CHI MINH CITY",
        "name": "SCHOOL OF BIOTECHNOLOGY",
        "portal": "Portal",
        "search": "Search",
        "about": "About",
        "admission": "ADMISSIONS",
        "academics": "ACADEMICS",
        "research": "RESEARCH",
        "students": "STUDENT",
        "news": "NEWS",
        "contact": "CONTACT",
        "overview": "Overview",
        "history": "History",
        "dean-s-welcome": "Dean's Welcome",
        "vision-and-mission": "Vision And Mission",
        "accreditation": "Accreditation",
        "organization": "Organization",
        "dean-office": "Dean Office",
        "secretariat": "Secretariat",
        "departments": "Departments",
        "departments-news": "Departments News",
        "depatment-of-biotechnology": "Depatment Of Biotechnology",
        "department-of-food-technology": "Department Of Food Technology",
        "department-of-applied-chemistry": "Department Of Applied Chemistry",
        "department-of-aquascience": "Department Of Aquascience",
        "laboratories": "Laboratories",
        "undergraduate-admission": "Undergraduate Admission",
        "graduate-admission": "Graduate Admission",
        "undergraduate-programs": "Undergraduate Programs",
        "dual-undergraduate-programs": "Dual Undergraduate Programs",
        "graduate-programs": "Graduate Programs",
        "bachelor-s-to-master-s-programs": "Bachelor's To Master's Programs",
        "twinning-programs": "Twinning Programs",
        "projects-and-publications": "Projects And Publications",
        "notable-research": "Notable Research",
        "hot-news": "Hot News",
        "academic-news": "Academic News",
        "research-news": "Research News",
        "students": "Students",
        "current-students": "Current Students",
        "academic-calendar": "Academic Calendar",
        "student-handbook": "Student Handbook",
        "class-cancellation": "Class Cancellation",
        "laboratory-registration-and-forms": "Laboratory Registration And Forms",
        "forms": "Forms",
        "scholarship-opportunities": "Scholarship Opportunities",
        "prospective-students": "Prospective Students",
        "admission-information": "Admission Information",
        "academic-program-information": "Academic Program Information",
        "alumni": "Alumni",
        "notable-alumni": "Notable Alumni",
        "alumni-news": "Alumni News",
        "departments-of": "Department Of",
        "biotechnology": "Biotechnology",
        "food-technology": "Food Technology",
        "applied-chemistry": "Applied Chemistry",
        "aquascience": "Aquascience",
        "promo": "EXPERIENCE ACTIVITIES",
        "reg-promo": "ENJOY OUR EXPERIENCE",
        "research": "Research",
        "view-all-posts": "View all posts",
        "view-all-events": "View all events",
        "contact": "Contact",
        "contact-name": "international university - school of biotechnology",
        "address-text": "Quarter 6, Linh Trung Ward, Thu Duc City, Ho Chi Minh City",
        "send-message": "send message",
        "message-contact": "Please leave any inquiries. We will contact you as soon as we receive it./.",
        "fullname": "fullname",
        "phone": "telephone",
        "email": "e-mail",
        "message": "message",
        "read-more": "read more",
        "mission": "Mission",
        "page": "Page",
        "links": "Links",
        "promo-text": "The Faculty of Biotechnology was established with the desire to bring the International University to the forefront of education and research in the fields of Biotechnology, Food Technology, Biochemistry, Fisheries Science, Chemical Engineering. and Biomedical Science.",
        "research-text": "Our mission is to effectively apply learning and research results to social development work.",
        "activities": "Activities",
        "document-form": "Document Form",
        "lecturers": "Lecturers",
        "manager-lecturers": "Manager & Lecturers",
        "education-program": "Education program",
        "career-opportunities": "Career Opportunities",
        "previous-admission-score": "Previous Admission Score",
        "strategic-partners": "Strategic Partners",
        "awards-and-products": "Awards & Products",
        "activities": "Activities",
        "student-list": "Student list",
        "student-handbook": "Student handbook",
        "internship-program": "Internship program",
        "thesis": "Thesis",
        "general-information": "General Information",
        "programs": "Programs",
        "twinning-programs": "Twinning programs",
        "biotechnology-program": "Biotechnology Program",
        "chemistry-biochemistry-program": "Chemistry (Biochemistry) Program",
        "food-technology-program": "Food Technology Program",
        "aquascience-program": "Aquascience Program",
        "twinning-university-of-nottingham": "Twinning With University of Nottingham",
        "twinning-university-of-the-west-of-england": "Twinning With University of the West of England",
        "admission_procedures": "Admission Procedures",
        "entrance_examination_groups": "Entrance Examination Groups",
        "list_of_admissions": "List of Admissions",
        "list_of_graduates": "List of Graduates",
        "biotechnology-biomedical-science-orientation": "Biotechnology (Biomedical Science Orientation)",
        "join-us": "Join Us",
        "outstanding-alumni": "Outstanding Alumni",
        "career-hub": "Career Hub",
    }
}